## Dense Layers

In [ ]:
#shape of dense layers
import tensorflow as tf
from tensorflow.keras.layers import Dense

In [ ]:
N, n_feature = 1, 10
tf.random.set_seed(10)
x = tf.random.normal(shape=(N, n_feature))

n_neuron = 3
dense = Dense(units = n_neuron, activation='sigmoid')
y = dense(x)

w, b = dense.get_weights()
print('==== input / weight / bias ====')
print('x: ', x.shape)
print('w: ', w.shape)
print('b: ', b.shape)
print('y: ', y.shape)

==== input / weight / bias ====
x:  (1, 10)
w:  (10, 3)
b:  (3,)
y:  (1, 3)


In [ ]:
#output calculations
N, n_feature = 4, 10
tf.random.set_seed(10)
x = tf.random.normal(shape=(N, n_feature))

n_neuron = 3
dense = Dense(units = n_neuron, activation='sigmoid')
y_tf = dense(x)
print('y(Tensorflow): \n', y_tf.numpy())

W, b = dense.get_weights()

# calculate with matrix multiplication
z = tf.linalg.matmul(x, W) + b
y_man = 1 / (1+tf.math.exp(-z))
print('y(with matrix multiplocation: \n', y_man.numpy())

import numpy as np
# calculate with dot products(옛날 방식)
y_man_vec = np.zeros(shape=(N, n_neuron))
for x_idx in range(N):
  x_ = x[x_idx]
  for nu_idx in range(n_neuron):
    w, b_ = W[:, nu_idx], b[nu_idx]
    z = tf.reduce_sum(x_ * w) + b_
    a = 1 / (1+np.exp(-z))
    y_man_vec[x_idx, nu_idx] = a
print('y(with got product): \n', y_man_vec)


y(Tensorflow): 
 [[0.88741076 0.28992727 0.35931098]
 [0.7775674  0.6703929  0.20458943]
 [0.4281316  0.61795133 0.45941862]
 [0.87215537 0.18618417 0.49994683]]
y(with matrix multiplocation: 
 [[0.8874107  0.28992724 0.35931098]
 [0.7775674  0.6703928  0.20458944]
 [0.42813158 0.61795133 0.4594186 ]
 [0.8721554  0.18618418 0.49994683]]
y(with got product): 
 [[0.8874107  0.28992724 0.35931102]
 [0.7775674  0.67039287 0.20458942]
 [0.4281316  0.61795135 0.45941861]
 [0.87215541 0.1861842  0.49994681]]


## Model Implementation

In [ ]:
# Model Implementation with Sequential Method
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

In [ ]:
model = Sequential()
model.add(Dense(units=10, activation='sigmoid')) #activation 지정 안하면 none임
model.add(Dense(units=20, activation='sigmoid'))

In [ ]:
n_neurons = [3,4,5,6]
model = list()
for n_neuron in n_neurons:
  model.apped(Dense(units=n_neuron, activation='sigmoid'))

model = Sequential()
for n_neuron in n_neurons:
  model.apped(Dense(units=n_neuron, activation='sigmoid'))

# 기본적으로 list나 sequential을 사용하는 것은 비슷
# sequential 클래스를 이용하면 여러가지 부가 기능이 있어서 좋음

In [ ]:
#model implementation with model-subclassing
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Model

In [ ]:
class TestModel(Model):
  def __init__(self):
    super(TestModel, self).__init__()
    self.dense1 = Dense(units=10, activation='sigmoid')
    self.dense2 = Dense(units=20, activation='sigmoid')
model = TestModel()
print(model.dense1)
print(model.dense2)

In [ ]:
# forward Propagation od models
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Model
from tensorflow.keras.models import Sequential

In [ ]:
tf.random.set_seed(10)
X = tf.random.normal(shape=(4,10))

#sequential method
model = Sequential()
model.add(Dense(units=10, activation='sigmoid'))
model.add(Dense(units=20, activation='sigmoid'))

Y = model(X)
print(Y.numpy())

#model-subclassing
class TestModel(Model): # 이 시점 w, b는 초기화 됨(기본은 랜덤)
  def __init__(self):
    super(TestModel, self).__init__() #class의 init method 호출 -> 초기화
    self.dense1 = Dense(units=10, activation='sigmoid')
    self.dense2 = Dense(units=20, activation='sigmoid')

  def call(self, x):
    x = self.dense1(x)
    x = self.dense2(x)
    return x

model = TestModel()
Y = model(x) # 이 시점 w, b는 초기화 됨(기본은 랜덤)
print(Y.numpy())

[[0.55650467 0.5736378  0.5630582  0.38230422 0.5800853  0.46750382
  0.5453265  0.572396   0.577736   0.5092679  0.63902617 0.41740972
  0.4959601  0.48987812 0.37868184 0.6252993  0.50767297 0.5675629
  0.4415443  0.5643339 ]
 [0.542635   0.5824134  0.55322725 0.41820836 0.45012072 0.4604416
  0.5349409  0.56532025 0.5037934  0.5493765  0.62485325 0.48017088
  0.4684742  0.44895202 0.44587284 0.58404434 0.40546966 0.5525067
  0.48883936 0.5321424 ]
 [0.5514741  0.54305255 0.5955268  0.39230984 0.49052256 0.4777674
  0.5909605  0.60162765 0.5510731  0.53855234 0.6518259  0.36644483
  0.46875128 0.42796102 0.42704153 0.62905306 0.47941467 0.5476874
  0.45441562 0.5198266 ]
 [0.55018824 0.6035677  0.54334694 0.37710547 0.553181   0.46198446
  0.5360454  0.57856405 0.5902688  0.49926516 0.6641064  0.46451893
  0.4757576  0.51785564 0.3944179  0.58145726 0.4373687  0.54021823
  0.46061313 0.6211433 ]]
[[0.40813234 0.42172378 0.41616654 0.61241937 0.52082723 0.4728814
  0.45194685 0.550679