## 역전파 학습 알고리즘

In [2]:
import numpy as np

In [3]:
# 활성화 함수
def actf(x):
    return 1 / (1+np.exp(-x))

# 활성화 함수 미분치(역)
def actf_deriv(x):
    return x * (1-x)

In [4]:
inputs, hiddens, outputs = 2, 2, 1
learning_rate = 0.2

#학습 샘플과 정답(XOR)
X = np.array([[0,0], [0,1], [1,0], [1,1]])
T = np.array([[0], [1], [1], [0]])

#훈련 데이터
W1 = np.array([[0.10, 0.20], [0.30, 0.40]])
W2 = np.array([[0.50], [0.60]])
B1 = np.array([0.1, 0.2])
B2 = np.array([0.3])

In [5]:
#순방향 전파 계산 
def predict(x):
    layer0 = X                   #입력값을 layer0에 대입
    Z1 = np.dot(layer0, W1) + B1 # 입력값에 대한 affine function계산 : 행렬곱
    layer1 = actf(Z1)            # 활성화 함수(시그모이드)
    Z2 = np.dot(layer1, W2) + B2 # layer1dp 대한 affine function계산 : 행렬곱
    layer2 = actf(Z2)            # 활성화 함수(시그모이드)
    return layer0, layer1, layer2

In [11]:
# 역전파 계산
def fit():
    global W1, W2, B1, B2
    for i in range(90000):
        for x, y in zip(X, T):
            x = np.reshape(x, (1, -1))
            y = np.reshape(y, (1, -1))
            
            layer0, layer1, layer2 = predict(x) #순방향 계산
            layer2_error = layer2 - y # 오차 계산
            layer2_delta = layer2_error * actf_deriv(layer2) #출력층의 델타 계산
            layer1_error = np.dot(layer2_delta, W2.T) #은닉층의 오차 계산
            layer1_delta = layer1_error * actf_deriv(layer1) # 은닉층의 델타 계산
            
            W2 += -learning_rate * np.dot(layer1.T, layer2_delta)
            W1 += -learning_rate * np.dot(layer0.T, layer1_delta)
            B2 += -learning_rate * np.sum(layer2_delta, axis=0)
            B1 += -learning_rate * np.sum(layer1_delta, axis=0)

In [12]:
def test():
    for x, y in zip(X,T):
        x = np.reshape(x, (1, -1))
        layer0, layer1, layer2 = predict(x)
        print(x, y, layer2)
fit()
test()

[[0 0]] [0] [[0.49937625]
 [0.49937898]
 [0.49937898]
 [0.49937898]]
[[0 1]] [1] [[0.49937625]
 [0.49937898]
 [0.49937898]
 [0.49937898]]
[[1 0]] [1] [[0.49937625]
 [0.49937898]
 [0.49937898]
 [0.49937898]]
[[1 1]] [0] [[0.49937625]
 [0.49937898]
 [0.49937898]
 [0.49937898]]
